name: Start Django App

on: [push, pull_request]

jobs:
  Ultimatetest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run django unittest
        run: |
          python githubactions/manage.py test actions.tests
